#!/bin/sh
bkr workflow-simple --variant=Server --systype=machine --arch=x86_64 --distro=RHEL-7.5-20170905.n.0 --tag=/distribution/dbrace/Sanity/Look-at-udev-rules --task=/distribution/dbrace/Sanity/Look-at-udev-rules --whiteboard=udev --debug --install=lsscsi --install=sg3_utils
